### ISSUE TITLE
Bugs in extract_characteristics.py

### ISSUE THREAD

**Issue by machengcheng2016** [xingjunm/lid_adversarial_subspace_detection#4]
Hello,
When I try to *python extract_characteristics.py -d cifar -a fgsm -r lid -k 20 -b 100*, there raises an error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: conv2d_1_input:0 is both fed and fetched.
Exception tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidArgumentError() in <bound method _Callable.__del__ of <tensorflow.python.client.session._Callable object at 0x7fc954672d50>> ignored
![image](https://user-images.githubusercontent.com/22851860/54528992-93441200-49b9-11e9-8eb9-190fe3fef5a4.png)
How can I fix this, please?

**Comment by xingjunm** [comment]
Hi, sorry for the late reply. This may caused by Tensorflow version, can you try python 3.5, tensorflow = 1.8?

**Comment by machengcheng2016** [comment]
Thanks for your reply!
I followed your advice and create a new conda environment, with python 3.5 and tensorflow-gpu 1.8. But still got an error:
![image](https://user-images.githubusercontent.com/22851860/54896530-b9a90680-4eff-11e9-94be-386912fa5e5f.png)
I also looked into some related technical blogs with this error, however, I was even more confused.
This is my *conda list* output, is there something inappropriate?
![image](https://user-images.githubusercontent.com/22851860/54896703-68e5dd80-4f00-11e9-85ca-5719ec6fa8dc.png)

**Comment by xingjunm** [comment]
Hi I don't have time to test and solve this bug for you. But I can give some directions to check.
1. According to the errors. It seems that one of, or all of the funcs defined here are some problemetic now:
for i, func in enumerate(funcs):
            X_act = func([X[start:end], 0])[0]
![image](https://user-images.githubusercontent.com/14815238/55049312-c3697000-509f-11e9-9c4f-5da83a964ea2.png)
I guess some problem happened to fetch the input layer data, e.g., conv2d_1: input 0:. I think it might caused by some changes in Tensorflow's backend, some how cannot fetch input data from the graph anymore. You can try remove the in the get_layer_wise_activations to not include the layers[0].input: acts = [model.layers[0].input] --> acts =[]. (This should do no harm to LID stuff).
![image](https://user-images.githubusercontent.com/14815238/55049512-a4b7a900-50a0-11e9-8d00-ba83741ed3a2.png)
Let's me know if this works or not.

**Comment by machengcheng2016** [comment]
It works after I change acts = [model.layers[0].input] --> acts =[].
Thanks a lot!

**Comment by liuyishoua** [comment]
l am confused. Why a simple thing could be described so hard? Although the logical in this paper is so pretty, l cant read it more. 1+1 equals 2, every knows, why come a word, XXX said :"1+1=2". l am confused, just for the rationalty and logical ?.
